[package]
name = "docker-engine"
version = "0.1.0"
edition = "2021"
publish = false
build = "../build.rs"

[lib]
path = "../packages.rs"

[package.metadata.build-package]
releases-url = "https://github.com/moby/moby/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/moby/moby/archive/v25.0.7/moby-25.0.7.tar.gz"
sha512 = "0ff0f8304780b57893400f95be9ac669c10f1bf47fe4953f852ae06cbf4ba98d4e6350110b97cfcbf6359eece37d39f729e929d760fdef7249e0af9d4844814e"

[build-dependencies]
glibc = { path = "../glibc" }
libseccomp = { path = "../libseccomp" }
systemd = { path = "../systemd" }
